name: unit-test

on:
  push:            # every push, any branch
    paths-ignore:
      - 'README.md'
  pull_request:    # every PR to main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.11']   # or ['3.10', '3.11'] for multi-version

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt         # if you have one
        pip install pytest numpy matplotlib

    - name: Run tests
      run: pytest -q
