name: unit-test
on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: { python-version: '3.13' }

    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install numpy matplotlib pytest

    - name: Run pytest
      env:
        PYTHONPATH: ${{ github.workspace }}   # <<< add this line
      run: pytest -q


